config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root :to => 'pages#index'

  match '/rti_requests/recent', to: 'rti_requests#recent', via: :get
  match '/rti_requests/top_viewed', to: 'rti_requests#top_viewed', via: :get

  resources :rti_requests, only: [:show]
  resources :tags, only: [:show]
  resources :public_authorities, only: [:show]
  resources :feedbacks, only: [:new, :create]

end

app/models/rti_request.rb
class RtiRequest < ActiveRecord::Base
  include GlobalConstants
  include UrlTokenable
  after_initialize :default_values

  is_impressionable :counter_cache => true, :column_name => :impressions_count, :unique => :session_hash


  ## Relations
  has_many :taggings, inverse_of: :rti_request, dependent: :destroy
  has_many :tags, through: :taggings
  belongs_to :public_authority, inverse_of: :rti_requests, counter_cache: true
  ## End Relations


  ## Validations
  validates :public_authority, presence: true

  validates :url_token, presence: true, uniqueness: {case_sensitive: true}, length: {is: 12}
  validates :title, presence: true, uniqueness: {case_sensitive: false}, length: {maximum: 250}

  validates :content, presence: true
  validates :filed_date, presence: true
  validates :source_url, presence: true, length: {maximum: 250}

  validates :publishp, inclusion: {in: GlobalConstants::TRUE_FALSE}
  validates :publish_datetime, presence: true

  validates :fb_publishedp, inclusion: {in: GlobalConstants::TRUE_FALSE}
  validates :twitter_publishedp, inclusion: {in: GlobalConstants::TRUE_FALSE}
  validates :gplus_publishedp, inclusion: {in: GlobalConstants::TRUE_FALSE}

  validates :impressions_count, presence: true, numericality: {only_integer: true}
  ## End Validations


  ## Callbacks
  ## End Callbacks


  ## Scopes
  scope :published_requests, -> {
    where(publishp: true)
      .where("publish_datetime <= ?", Time.now)
  }
  scope :top_viewed, -> {
    order(impressions_count: :desc, id: :desc)
      .published_requests
      .includes(:tags)
  }

  scope :trending, -> {
    where("updated_at > ?", Time.now - 30.days)
      .top_viewed
  }

  scope :recent, -> {
    order(filed_date: :desc, id: :desc)
      .published_requests
      .includes(:tags)
  }
 
  scope :get_todays_rtis, -> {where("DATE(publish_datetime)=DATE(?) and ",Time.now.utc)}
  ## End Scopes


  private
  def default_values
    if new_record?
      self.filed_date = Time.now
      self.publishp = false
      self.publish_datetime = Time.now
      self.fb_publishedp = false
      self.twitter_publishedp = false
      self.gplus_publishedp = false
      self.impressions_count ||= 0
    end
  end

  rails_admin do
    edit do
      field :title
      field :content, :ck_editor
      field :filed_date
      field :source_url
      field :public_authority
      field :publishp
      field :publish_datetime
      field :fb_publishedp
      field :twitter_publishedp
      field :gplus_publishedp
      field :tags
    end
  end

end

app/controllers/rti_requests_controller.rb
class RtiRequestsController < ApplicationController
 include UrlTokenableController

  def show
    # @rti_request = RtiRequest.find_by_url_token(params[:id])
    @rti_request = search_by_url_token(RtiRequest.name.classify.constantize, params)
    if !@rti_request.nil?
      impressionist(@rti_request, "message", unique: [:session_hash])
      #@rti_request.touch
    else
      raise ActiveRecord::RecordNotFound
      # raise ActionController::RoutingError.new('Not Found')
    end
  end

  def recent
    @rti_requests = RtiRequest.recent.page(params[:page])
    render "pages/index"
  end

  def top_viewed
    @rti_requests = RtiRequest.top_viewed.page(params[:page])
    render "pages/index"
  end

  def rssFeed
   @posts= RtiRequest.recent.limit(15)
   respond_to do |format|
    format.atom {render layout:false }
   end
  end

end

app/helpers/rti_requests_helper.rb
module RtiRequestsHelper
end

app/views/rti_requests/_rti_request.html.erb
<div class="jumbotron rti_request_partial">

  <p class="title"> <%= link_to rti_request.title, rti_request %> </p>
  <p> <%=raw rti_request.content %> </p>

  <p>
    <% rti_request.tags.each do |tag| %>
    <%= link_to "#" + tag.name, tag_path(tag) %>
    <% end %>
  </p>

  <div class="fb-like" data-href="http://www.rtidatabase.com/rti_requests/<%= rti_request.url_token %>" data-layout="standard" data-action="like" data-show-faces="true" data-share="true"></div>

  <div class="g-plusone" data-annotation="inline" data-width="300" data-href="http://www.rtidatabase.com/rti_request/<%= rti_request.url_token %>"></div>
</div>

app/views/rti_requests/show.html.erb
<%= render :partial => 'shared/head_meta', :locals => {:isHome => false, :page=> @rti_request} %>
<div class="jumbotron rti_request_partial">
  <span class="label label-default">Dated: <%= @rti_request.filed_date.to_formatted_s(:long_ordinal) %></span>
  <span class="label label-default">Views: <%= @rti_request.impressions_count %></span>

  <p class="title"><%= @rti_request.title %></p>
  <p><%=raw @rti_request.content %></p>

  <p><span class="public_authority_label"><span class="italic-font"> Public Authority: </span><%= link_to @rti_request.public_authority.name, public_authority_path(@rti_request.public_authority) %></span> </p>

  <p><span class="italic-font">Source: </span><%= link_to @rti_request.source_url, @rti_request.source_url %></p>

  <p>
    <% @rti_request.tags.each do |tag| %>
    <%= link_to "#" + tag.name, tag_path(tag) %>
    <% end %>
  </p>

  <div class="fb-like" data-href="http://www.rtidatabase.com/rti_requests/<%= @rti_request.url_token %>" data-layout="standard" data-action="like" data-show-faces="true" data-share="true"></div>

  <div class="g-plusone" data-annotation="inline" data-width="300" data-href="http://www.rtidatabase.com/rti_request/<%= @rti_request.url_token %>"></div>

</div>

<div class="fb-comments" data-href="http://www.rtidatabase.com/rti_requests/<%= @rti_request.url_token %>" data-numposts="5" data-width="100%"></div>