config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root :to => 'pages#index'

  match '/rti_requests/recent', to: 'rti_requests#recent', via: :get
  match '/rti_requests/top_viewed', to: 'rti_requests#top_viewed', via: :get

  resources :rti_requests, only: [:show]
  resources :tags, only: [:show]
  resources :public_authorities, only: [:show]
  resources :feedbacks, only: [:new, :create]

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <ul class="errors">
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
  </ul>
<% end %>

app/views/shared/_head_css_js.html.erb
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true, async: true %>
<%= csrf_meta_tags %>

app/views/shared/_head_meta.html.erb
<!-- from bootstrap basic template -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">


<% if isHome ==true && page.nil?  %>
<% content_for :head do %>
         <meta name="description" content="A database of all RTI(Right to information act) questions and response from various Indian government departments.View RTI filings online from across states and departments. " />
         <meta name="keywords" content="rti,right to information act,rti filings,rti database,rti pages,rti forms,rti online,rti online free,india rti,rti indian,rti free,rti documents,rti book,rti pdf" />
	 <meta property="og:title" content="RTIDatabase"/>
         <meta property="og:type" content="article"/>	
	 <meta property="og:url" content="https://www.rtidatabase.com"/>	
	 <meta property="og:image" content="http://www.rtidatabase.com/images/rtidatabase_logo.jpg"/>
	 <meta property="og:description" content="A database of all RTI(Right to information act) questions and response from various Indian government departments.View RTI filings online from across states and departments." />
	<meta property="fb:admins" content="<%#TODO%>"/>

	<meta itemprop="name" content="RTIDatabase">
	<meta itemprop="description" content="A database of all RTI(Right to information act) questions and response from various Indian government departments.View RTI filings online from across states and departments.">
	<meta itemprop="image" content="http://www.rtidatabase.com/images/rtidatabase_logo.jpg">

	<link rel="publisher" href="https://plus.google.com/<%#TODO%>"/>
	<meta name="author" content="rtidatabase" />
	<meta name="copyright" content="rtidatabase" />
	<meta name="application-name" content="RTIDatabase" />
	<meta name="description" content="A database of all RTI(Right to information act) questions and response from various Indian government departments.View RTI filings online from across states and departments." />
	<meta name="keywords" content="rti,right to information act,rti filings,rti database,rti pages,rti forms,rti online,rti online free,india rti,rti indian,rti free,rti documents,rti book,rti pdf" />


         <meta name="twitter:card" content="summary" />
         <meta name="twitter:site" content="@RTIDatabase" />
         <meta name="twitter:title" content="RTIDatabase" />
         <meta name="twitter:description" content="A database of all RTI(Right to information act) questions and response from various Indian government departments.View RTI filings online from across states and departments. @RTIDatabase" />
         <meta name="twitter:image" content="http://www.myshortflicks.com/images/rtidatabase_logo.jpg" />
         <meta name="twitter:url" content="https://www.rtidatabase.com" />


<% end %> 
<% elsif isHome ==false && !page.nil? && page.instance_of?(RtiRequest)%>

<% content_for :head do %>
	 <meta property="og:title" content="<%=page.title.truncate(70)%>"/>	
	 <meta property="og:url" content="<%#TODO%>"/>	
	 <meta property="og:image" content="http://www.myshortflicks.com/images/rtidatabase_logo.jpg"/>
	 <meta property="og:description" content="<%=page.content.truncate(150)%>" />

	<meta name="author" content="<%=page.title.truncate(70)%>" />
	<meta name="copyright" content="RTIDatabase" />
	<meta name="application-name" content="RTIDatabase" />
	<meta name="description" content="<%=page.content.truncate(150)%>" />
	<meta name="keywords" content="<%=page.title.truncate(70)%>" />

         <meta name="twitter:card" content="summary" />
         <meta name="twitter:site" content="@RTIDatabase" />
         <meta name="twitter:title" content="<%=page.title.truncate(70)%>" />
         <meta name="twitter:description" content="<%=page.content.truncate(150)%>" />
         <meta name="twitter:image" content="http://www.myshortflicks.com/images/rtidatabase_logo.jpg" />
         <meta name="twitter:url" content="<%#TODO%>" />

	<meta itemprop="name" content="<%=page.title.truncate(70)%>">
	<meta itemprop="description" content="<%=page.content.truncate(150)%>">
	<meta itemprop="image" content="http://www.rtidatabase.com/images/rtidatabase_logo.jpg">


<% end %> 

<%end%>

app/views/shared/_header.html.erb
<div class="navbar-wrapper">
  <div class="container">

    <nav class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "RTI Database (beta)", root_path, class: "navbar-brand" %>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">

            <li class= <%= 'active' if current_page?(root_path) %> > <%= link_to "Home", root_path %> </li>
            <li class= <%= 'active' if current_page?(rti_requests_recent_path) %> > <%= link_to "Recent", rti_requests_recent_path %> </li>
            <li class= <%= 'active' if current_page?(rti_requests_top_viewed_path) %> > <%= link_to "Top Viewed", rti_requests_top_viewed_path %> </li>
            <li class= <%= 'active' if current_page?(new_feedback_path) %> > <%= link_to "Feedback", new_feedback_path %> </li>

          </ul>
        </div>
      </div>
    </nav>
    <p class="text-right">
      Follow/Contact us:
      <%= link_to image_tag("fb_icon.png", alt: "fb_icon", size: "30x30"), "https://www.facebook.com/rtidatabase", target: "_blank" %>
      <%= link_to image_tag("google_icon.png", alt: "google_icon", size: "30x30"), "https://plus.google.com/u/0/b/108596900179837935987/108596900179837935987", target: "_blank" %>
      <%= link_to image_tag("twitter_icon.png", alt: "twitter_icon", size: "30x30"), "https://twitter.com/rtidatabase", target: "_blank" %>
    </p>
  </div>
</div>

<hr class="featurette-divider">

app/views/shared/_notice.html.erb
<% if flash[:notice] %>
<div class="alert alert-info" role="alert"><%= flash[:notice] %></div>
<% end %>

app/views/shared/_sn_js.html.erb
<!-- facebook sdk -->
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.3&appId=917256511669887";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<!-- for google recaptca -->
<script src='https://www.google.com/recaptcha/api.js'></script>


<!-- for google analyics -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-64530353-1', 'auto');
  ga('send', 'pageview');

</script>

<!-- for google +1 button  -->
<script src="https://apis.google.com/js/platform.js" async defer></script>